### ISSUE TITLE
can extract pdz file

### ISSUE THREAD

**Issue by bducraux** [fligt/read_pdz#3]
Error:
Error while reading last block! 
Stop index: 16777251 does not match total file size: 8550

check_pdz_file response:
pdz11_with_unexpected_filesize_8550_bytes

Could someone please help me fix this?

Thank's in advance.

**Comment by fligt** [comment]
Hi Bruno,

Thanks for reporting the issue!

Your pdz file seems to be a legacy pdz11 file. However with a file size
that I did not yet encounter. It appears that Bruker many variations of pdz
files with inconsistent file structures. Big mess.

Can you send the pdz file to me? Then I will try to parse it and update the
code accordingly.

With kind regards,

Frank Ligterink

Op vr 6 sep 2024 om 20:44 schreef Bruno Ducraux ***@***.***>

**Comment by bducraux** [comment]
Hi Frank,

Thanks for your quick answer.


Here are the files that I am facing the error:
[files.zip](https://github.com/user-attachments/files/16936273/files.zip)

**Comment by bducraux** [comment]
Hi Frank,

Could you reproduce the bug with the files?

here is my contact:
bruno.drx@gmail.com

Please let me know if I can help you anyhow.

kind regards

**Comment by fligt** [comment]
Hi Bruno, 

I fixed the problem. It turns out that the length of pdz11 files **is not fixed** as I thought. See [Pdz archeology](https://fligt.github.io/read_pdz/pdz-archeology.html) section in the documentation. I have uploaded the latest version of `read-pdz` to pypi.org. Would you be so kind to update with 

  ```bash
pip install -U read-pdz
```

and test if this now works with your files? Thanks again for reporting the issue! 

With kind regards, 
Frank

**Comment by bducraux** [comment]
Hi Frank,

Unfortunately, the function extract_spectra() still has the same error:

Extracting: 59.pdz
Error while reading last block!
Stop index: 16777251 does not match total file size: 8550
Error: list index out of range

Do you know if this function works with this legacy file?

Kind regards,

Bruno


Here is my test code:

from read_pdz import multiparse, check_pdz_type, extract_spectra

from read_pdz import file_to_bytes, get_blocks, parse

file1 = '00025-Limestone.pdz'
file2 = '59.pdz'
file3 = 'A1_a.pdz'
file4 = 'A7_a.pdz'
file5 = 'B5_a.pdz'
file6 = 'B11_a.pdz'

file_path = '/home/bducraux/Projects/read_pdz/samples/'

files = [file1, file2, file3, file4, file5, file6]

def check_files():
    for file in files:
        check = check_pdz_type(file_path + file)

        print(f"File: {file}")
        print(f"Check: {check}")

def extract_files():
    print('\n')
    print('Extracting spectra...')
    for file in files:
        print(f"Extracting: {file}")
        try:
            extract_spectra(file_path + file)
        except Exception as e:
            print(f"Error: {e}")
            continue

if __name__ == '__main__':
    check_files()
    extract_files()



Here the response:
(.venv) ***@***.***:~/Projects/read_pdz$ python test.py
File: 00025-Limestone.pdz
Check: pdz25
File: 59.pdz
Check: pdz11_2048_channels
File: A1_a.pdz
Check: pdz11_2048_channels
File: A7_a.pdz
Check: pdz11_2048_channels
File: B5_a.pdz
Check: pdz11_2048_channels
File: B11_a.pdz
Check: pdz11_2048_channels


Extracting spectra...
Extracting: 00025-Limestone.pdz
Saving spectral data to:
/home/bducraux/Projects/read_pdz/samples/00025-Limestone.pdz.csv
Extracting: 59.pdz
Error while reading last block!
Stop index: 16777251 does not match total file size: 8550
Error: list index out of range
Extracting: A1_a.pdz
Error while reading last block!
Stop index: 16777251 does not match total file size: 8550
Error: list index out of range
Extracting: A7_a.pdz
Error while reading last block!
Stop index: 16777251 does not match total file size: 8550
Error: list index out of range
Extracting: B5_a.pdz
Error while reading last block!
Stop index: 16777251 does not match total file size: 8550
Error: list index out of range
Extracting: B11_a.pdz
Error while reading last block!
Stop index: 16777251 does not match total file size: 8550
Error: list index out of range


Em sex., 13 de set. de 2024 às 11:22, Frank Ligterink <
***@***.***> escreveu:

**Comment by fligt** [comment]
Hi Bruno, 

Good to see that the checking the pdz type is working for you. I did not yet implement the detection of legacy files in the extract_spectra() function. However that should be fairly simple now. 

I will come back to you as soon as I updated that function.

**Comment by fligt** [comment]
Hi Bruno, 

I implemented legacy pdz11 support in the `extract_spectrum()` function. And pushed the latest read-pdz package (version 0.0.5) to the pypi.org. 

Would you be so kind to update the package and test again with your files?

**Comment by bducraux** [comment]
Hi Frank,


It is working perfectly now.

Great job!

Thank you!

Em sáb., 21 de set. de 2024 às 09:26, Frank Ligterink <
***@***.***> escreveu:
